### ISSUE TITLE
Widget light-color failing with invalid config

### ISSUE THREAD

**Issue by frode** [igorgladkov/rotini#35] opened 2016-01-11 22:13 UTC
Light-color widget is failing with invalid config and this message:
Item: "default" has invalid state

All the other light widgets for the hue bulb is functioning fine, and the color widget was working in a previous version..

Configs:

Sitemap

 Frame label="Lights Color {widget:light-color}" {
   Colorpicker item=Color_1
 }

Item

Color Color_1     "Guest toilet"   (Colorize, Hue)  {hue="1"}

**Comment by anordvall** [comment] 2016-01-11 22:19
This widget started working for me this morning after the client update, but now I also get the same invalid configuration error message as you.

**Comment by frode** [comment] 2016-01-11 22:27
Have the same issue for both openHAB 1.7 and 1.8.

**Comment by igorgladkov** [comment] 2016-01-11 22:55
@anordvall you're saying that it stopped working today without any changes in sitemap or items?

**Comment by anordvall** [comment] 2016-01-11 23:03
Ok I just used the colorpicker in standard openHAB app and changed the color. Then the widget started to work in Rotini as well.

**Comment by igorgladkov** [comment] 2016-01-11 23:04
That's helpful, must be state related (there is already a bug in that area)

**Comment by frode** [comment] 2016-01-11 23:20
I also got it working after changing color with the default openhab android app. So it is state related.

**Comment by igorgladkov** [comment] 2016-01-12 05:31
@frode @anordvall is there anything that sets state of the Color item that is not valid color state (e.g. nothing like "0.0,0.0,0.0"), from rules maybe?

**Comment by igorgladkov** [comment] 2016-01-12 05:39
I pushed new version 0.2.18 with some changes to state processing, let me know if that changes anything. I couldn't reproduce the issue, so not sure if that fixes it.

**Comment by anordvall** [comment] 2016-01-12 08:14
Nothing that I can think of. However, I realize that I had forgot to add my RGBW item to the persistance list (like I have done with all other lights) so I have done that now which should also work around the problem.

**Comment by frode** [comment] 2016-01-13 09:44
@igorgladkov i checked the state of a light-color item that is resulting as invalid config, could this value be causing the problem?

0.000000,0.000000,100.000000

**Comment by igorgladkov** [comment] 2016-01-13 17:41
@frode no, that one is definitely a correct value

**Comment by frode** [comment] 2016-01-19 08:57
Tried again today (calling rest service with item directly in chrome). 

Initial state (returns invalid config):

<item>
<type>ColorItem</type>
<name>Color_1</name>
<state>0.0,0.0,0.0</state>
<link>http://192.168.1.82:8080/rest/items/Color_1</link>
</item>

Change color temp with habdroid:

<item>
<type>ColorItem</type>
<name>Color_1</name>
<state>0.0,0.0,50.196083</state>
<link>http://192.168.1.82:8080/rest/items/Color_1</link>
</item>

After updating the value with habdroid, rotini picks up the value and the widget renders correctly.

@igorgladkov  Perhaps you need to handle single digit value in the decimal values?

**Comment by igorgladkov** [comment] 2016-01-20 19:03
@frode "0.0,0.0,0.0" state is working for me. Can you post output of http://192.168.1.82:8080/rest/sitemaps/{sitemap_name}/{tab_number_as_##} of that item, when item is failing?

**Comment by igorgladkov** [comment] 2016-02-10 17:53
0.3.26 shows what state was received from the server in error popup.
Valid state from the server should be in HSB format, e.g. "0.0,0.0,0.0", anything else means that server setup is not correct.

Since I could only reproduce the error when state is truly invalid I'm going to close this, feel free to re-open with additional information.

**Closed as completed by igorgladkov** 2016-02-10 17:53 UTC
Labels: bug

**Comment by igorgladkov** [comment] 2016-02-13 14:48
Explanation: seems the issue is with rrd4j persistence on color item, because it only works with numbers on restore the value becomes a decimal instead of string in HSB format (see: https://plus.google.com/u/0/111923515631072106738/posts/ah7rbUpEd8c)
