### ISSUE TITLE
Fails to switch to remote connection

### ISSUE THREAD

**Issue by frode** [igorgladkov/rotini#142] opened 2016-06-27 08:16 UTC
It seems to be a problem when you are on a LAN where you are assigned the same IP range used by the local openhab server config, app doesnt switch to remote connection after it fails to connect to a local IP.

As soon as I turn off the wifi on my cellphone, the remote connection is established.

So I guess the mechanism needs to be tweaked to connect remotely if the local IP connection fails? 
Alternatively add settings to only use LAN connection when you are on a known SSID..

**Comment by igorgladkov** [comment] 2016-06-27 14:48
Duplicate of #125

**Closed as completed by igorgladkov** 2016-06-27 14:48 UTC
Labels: duplicate
