### ISSUE TITLE
Swipe-to-refresh makes widgets shrink

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#143] opened 2016-06-28 18:51 UTC
Every time (up to a few times) i swipe to refresh, all widgets horizontally shrink a bit. Can mail a video if that helps.

Also, the widgets does not fill the screen horizontally at start. It's ~1/2 cm of border on the right side of the screen.

Device: Asus ZenPad 10
Sitemap density: moderate

I do not see the shrink issue when using standard or compact density.

**Comment by igorgladkov** [comment] 2016-06-28 19:31
Can you post screenshots of right side border?
Are you in fullscreen mode?

**Comment by anordvall** [comment] 2016-06-28 19:57
Initially:

![20160628_215448](https://cloud.githubusercontent.com/assets/13090236/16430273/18dabebc-3d7b-11e6-90cf-61dd5590470c.jpg)

After swiping 4-5 times:
![20160628_215458](https://cloud.githubusercontent.com/assets/13090236/16430280/26e5dfd2-3d7b-11e6-84df-6fdecf063b0b.jpg)

**Comment by igorgladkov** [comment] 2016-06-29 02:14
Tried it on bunch of devices can't reproduce it yet. What is the OS on that?

**Comment by spacemanspiff2007** [comment] 2016-06-29 08:37
For me it changes the transparency.
E.g. the items get darker.

**Comment by igorgladkov** [comment] 2016-06-29 13:56
@spacemanspiff2007 That one was fixed in 0.11.71 release

**Comment by anordvall** [comment] 2016-06-29 16:19
Igor, FYI I just noticed that this issue isn't related to swipe-to-refresh. The shrinking of the widgets happens also if one widget gets updated. Not if you click on it in Rotini, but if it updates due to external change of the item.

**Comment by anordvall** [comment] 2016-06-29 16:24
The OS is Android 5.0.2

**Comment by igorgladkov** [comment] 2016-07-01 03:57
@anordvall I couldn't reproduce it still, but I did change some behavior in 0.13 that might fix this.

**Comment by igorgladkov** [comment] 2016-07-03 14:40
@anordvall New version is released, please let me know if that fixes it.

**Comment by anordvall** [comment] 2016-07-03 18:16
Problem fixad and now the widgets also fill the whole screen horizontally again. Many thanks Igor! :)

**Closed as completed** 2016-07-03 18:17 UTC
Labels: bug, investigate
